config/routes.rb
Basecamp::Application.routes.draw do

  resources :lists do
    resources :tasks
  end

  resources :projects

    root :to => "projects#index"
  devise_for :users

end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :title, :project_id
  validates_presence_of :title, :project

  belongs_to :project
  has_many :tasks
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :title, :user_id, :public

  validates_presence_of :title, :on => :create, :message => "can't be blank"
  validates_presence_of :user_id, :on => :create, :message => "can't be blank"
  validates_presence_of :public, :on => :create, :message => "can't be blank"
  belongs_to :user
  has_many :lists
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :description
  validates_presence_of :description

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list = List.new
    @project_id = params[:project_id]
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
  end

  def destroy
  end

  def create
    @project = Project.find(params[:list][:project_id])
    @list = List.new(params[:list])
    respond_to do |format|
      if @list.save
        format.html { redirect_to project_path(@project) }
        format.js
      else
        format.html { render 'new' }
        format.js
      end
    end
  end

  def show
    @list = List.find(params[:id])
    @task = Task.new
  end

  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def new
    @project = Project.new
  end

  def edit

  end

  def destroy
  end

  def update
  end

  def index
    @projects = Project.where(current_user.id)
  end

  def show
    @list = List.new
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      flash[:success] = "Success!"
      redirect_to project_path(@project)
    else
      redirect_to new_project_path, :alert => "Project must have a title and a public status."
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
  end

  def new
  end

  def show
  end

  def create
    @list = List.find(params[:list_id])
    @task = @list.tasks.new(params[:task])
    respond_to do |format|
      if @task.save
        # flash[:success] = "Success!"
        format.html { redirect_to(@list, :notice =>  "Success!") }
        format.js
      else
        format.html { redirect_to list_path(@list) , :alert => "Project must have a title and a public status." }
        format.js
      end
    end
  end

  def destroy
  end

  def update
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Basecamp" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>


  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Basecamp</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Home", projects_path  %></li>
              <li><%= link_to "Create a New Project", new_project_path  %></li>
            </ul>
            <div class = "nav pull-right">
              <% if user_signed_in? %>
                <li><a>Signed in as <%= current_user.email %></a></li>
                <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
              <% else %>
                <li><%= link_to "Sign up", new_user_registration_path %></li>
                <li><%= link_to "Sign in", new_user_session_path %></li>
              <% end %>
            </div>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
              <%= content_tag :p, flash[:success], :class => "flash notice" if flash[:success] %>
              <%= content_tag :p, flash[:notice], :class => "flash notice" if flash[:notice] %>
              <%= content_tag :p, flash[:alert], :class => "flash alert" if flash[:alert] %>
              <%= yield %>
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; BC Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/lists/_list.html.erb
<li><%=link_to list.title, list %></li>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/create.js.erb
$(".lists").append(" <%=j render(:partial => 'list', :locals => { :list => @list }) %>")

app/views/lists/destroy.html.erb
<h1>Lists#destroy</h1>
<p>Find me in app/views/lists/destroy.html.erb</p>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

app/views/lists/index.html.erb
<h1>Lists#index</h1>
<p>Find me in app/views/lists/index.html.erb</p>

app/views/lists/new.html.erb
<div class="hero-unit" align="center">
<h1>Create a new To-do List</h1>
<% if @list.errors.any? %>
  <ul>
    <% @list.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for @list do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.hidden_field :project_id, :value => @project_id %><br/>
  <%= f.submit %>
<% end %>
</div>

app/views/lists/show.html.erb
<div class="span9">
  <div class="hero-unit" align="center">
    <h1><%= @list.title %></h1>
    <div class="tasks">
      <% @list.tasks.each do |task| %>
        <li><%= task.description %></li>
      <% end %>
    </div>
  </div>
</div>
<div class="span3">
  <div class="well" align="center">
    <h2> Add tasks to your to-do list </h2>
    <br>
    <%= form_for [@list,@task], :remote => true do |f| %>
      <%= f.label :description %>
      <%= f.text_field :description, :style => "width: 175px", :class => "submittable" %>
      <br>
      <%= f.submit class: "btn btn-primary"%>
    <% end %>
  </div>
</div>

app/views/lists/update.html.erb
<h1>Lists#update</h1>
<p>Find me in app/views/lists/update.html.erb</p>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
<div class="hero-unit" align="center">
  <% if @projects %>
  <h1>Your Projects</h1>
  <br>
  <div class="projects">
    <% @projects.each do |project| %>
      <i class ="icon-globe"></i> <%= link_to project.title, project_path(project) %><br/>
    <% end %>
  </div>
    <% else %>
    <h1>You have no projects</h1>
  <% end %>
</div>

app/views/projects/new.html.erb
<div class="hero-unit" align="center">
  <h2>Create a new project</h2>
  <br>
  <%= form_for @project do |f| %>
    <h3>Title</h3>
    <%= f.text_field :title %>
    <br>
    <%= f.label :public, "Private" %>
    <%= f.radio_button :public, 0 %>
    <%= f.label :public, "Public" %>
    <%= f.radio_button :public, 1 %>
    <br>
    <br>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.submit class: "btn btn-primary"%>
  <% end %>
</div>

app/views/projects/show.html.erb
<div class="span9">
  <div class="hero-unit" align="center">
    <h1><%= @project.title %></h1>
    <br>
    Creator: <%= @project.user.email %>
    <div class="lists">
      <% @project.lists.each do |list| %>
        <div id=<%= list.id %>>
         <li><%=link_to list.title, list %>

         <%= link_to "Edit", edit_list_path %></li>
        </div>
      <% end %>

    </div>
  </div>
</div>
<div class="span3">
  <div class="well" align="center">
    <h2>Add Todo Lists to your project</h2><br>
    <%= form_for @list, :remote => true  do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title, :style => "width: 175px" %>
      <%= f.hidden_field :project_id, :value => params[:id] %><br/>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>

app/views/tasks/_task.html.erb
<li><%= @task.description%></li>

app/views/tasks/create.js.erb
$(".tasks").append("<%=j render(:partial => 'task', :locals => {:new_task => @task }) %>")

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<p>Find me in app/views/tasks/index.html.erb</p>

app/views/tasks/new.html.erb
<h1>Tasks#new</h1>
<p>Find me in app/views/tasks/new.html.erb</p>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>